In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
filepath = Path("Resources/Airbnb_Open_Data.csv")
clean_airbnb_df = pd.read_csv(filepath)
clean_airbnb_df.head()

C:\Users\divya\AppData\Local\Temp\ipykernel_34884\3416165177.py:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_airbnb_df = pd.read_csv(filepath)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [3]:
clean_airbnb_df['id'].value_counts()
clean_airbnb_df['id'].nunique()

102058

In [4]:
id_cleaned_df = clean_airbnb_df.drop_duplicates(subset=['id'],keep='first')
id_cleaned_df['id'].value_counts()

id
1001254     1
38582590    1
38581485    1
38580933    1
38580380    1
           ..
19789477    1
19788925    1
19788373    1
19787821    1
57367417    1
Name: count, Length: 102058, dtype: int64

In [5]:
id_cleaned_df.count()

id                                102058
NAME                              101808
host id                           102058
host_identity_verified            101769
host name                         101654
neighbourhood group               102029
neighbourhood                     102042
lat                               102050
long                              102050
country                           101526
country code                      101927
instant_bookable                  101953
cancellation_policy               101982
room type                         102058
Construction year                 101844
price                             101811
service fee                       101785
minimum nights                    101658
number of reviews                 101875
last review                        86226
reviews per month                  86240
review rate number                101739
calculated host listings count    101739
availability 365                  101610
house_rules                        50216
license                                2
dtype: int64

In [6]:
dropna_df = id_cleaned_df.dropna(subset=['host_identity_verified', 'lat','long','neighbourhood group','instant_bookable','cancellation_policy',
                      'room type','Construction year','price','last review','review rate number','calculated host listings count'])
dropna_df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102041,57358580,Cozy home away from home,60176837202,verified,NaN,Queens,Edgemere,40.59380,-73.77373,United States,...,$189,1.0,76.0,6/27/2019,2.84,1.0,1.0,324.0,NaN,NaN
102042,57359133,Central Park Views - Private Room & Bathroom,68411243647,verified,NaN,Manhattan,Upper West Side,40.79712,-73.96117,United States,...,$141,1.0,4.0,8/15/2017,0.14,4.0,1.0,0.0,My roommates and I take a lot of pride in keep...,NaN
102043,57359685,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,verified,NaN,Manhattan,SoHo,40.72318,-74.00223,United States,...,$209,2.0,21.0,7/1/2019,0.74,4.0,2.0,343.0,#NAME?,NaN
102044,57360237,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,verified,NaN,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,...,$162,31.0,4.0,5/29/2019,0.16,1.0,1.0,178.0,NaN,NaN
102057,57367417,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,...,NaN,4.0,22.0,6/15/2019,0.85,4.0,1.0,238.0,Please remember that this is a residential bui...,NaN

In [7]:
yearday_airbnb_df = dropna_df.loc[dropna_df['availability 365'] <= 365,:]
yearday_airbnb_df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102041,57358580,Cozy home away from home,60176837202,verified,NaN,Queens,Edgemere,40.59380,-73.77373,United States,...,$189,1.0,76.0,6/27/2019,2.84,1.0,1.0,324.0,NaN,NaN
102042,57359133,Central Park Views - Private Room & Bathroom,68411243647,verified,NaN,Manhattan,Upper West Side,40.79712,-73.96117,United States,...,$141,1.0,4.0,8/15/2017,0.14,4.0,1.0,0.0,My roommates and I take a lot of pride in keep...,NaN
102043,57359685,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,verified,NaN,Manhattan,SoHo,40.72318,-74.00223,United States,...,$209,2.0,21.0,7/1/2019,0.74,4.0,2.0,343.0,#NAME?,NaN
102044,57360237,Lovely Two Bedroom & Event Space From Nonprofit,83006936257,verified,NaN,Brooklyn,Bedford-Stuyvesant,40.69095,-73.93444,United States,...,$162,31.0,4.0,5/29/2019,0.16,1.0,1.0,178.0,NaN,NaN
102057,57367417,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,...,NaN,4.0,22.0,6/15/2019,0.85,4.0,1.0,238.0,Please remember that this is a residential bui...,NaN

In [8]:
yearday_airbnb_df['neighbourhood group'].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'Queens', 'Bronx',
       'Staten Island'], dtype=object)

In [9]:
yearday_airbnb_df['neighbourhood group'].value_counts()

neighbourhood group
Brooklyn         34298
Manhattan        34199
Queens           11132
Bronx             2281
Staten Island      824
brookln              1
Name: count, dtype: int64

In [10]:
yearday_airbnb_df['neighbourhood group']= yearday_airbnb_df['neighbourhood group'].replace({'brookln':'Brooklyn'})
yearday_airbnb_df['neighbourhood group'].value_counts()

C:\Users\divya\AppData\Local\Temp\ipykernel_34884\3639175684.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['neighbourhood group']= yearday_airbnb_df['neighbourhood group'].replace({'brookln':'Brooklyn'})

neighbourhood group
Brooklyn         34299
Manhattan        34199
Queens           11132
Bronx             2281
Staten Island      824
Name: count, dtype: int64

In [11]:
yearday_airbnb_df['service fee'] = yearday_airbnb_df['service fee'].fillna(0)

yearday_airbnb_df['service fee']

C:\Users\divya\AppData\Local\Temp\ipykernel_34884\2935290641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['service fee'] = yearday_airbnb_df['service fee'].fillna(0)

0         $193
1          $28
3          $74
4          $41
7         $212
          ...
102041    $189
102042    $141
102043    $209
102044    $162
102057       0
Name: service fee, Length: 82735, dtype: object

In [12]:
yearday_airbnb_df['price'] = yearday_airbnb_df['price'].str.replace("$","")
yearday_airbnb_df['price'] = yearday_airbnb_df['price'].str.replace(",","")
yearday_airbnb_df['price'] = pd.to_numeric(yearday_airbnb_df['price'])
yearday_airbnb_df['price']

C:\Users\divya\AppData\Local\Temp\ipykernel_34884\1465490396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['price'] = yearday_airbnb_df['price'].str.replace("$","")
C:\Users\divya\AppData\Local\Temp\ipykernel_34884\1465490396.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['price'] = yearday_airbnb_df['price'].str.replace(",","")
C:\Users\divya\AppData\Local\Temp\ipykernel_34884\1465490396.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['price'] = pd.to_numeric(yearday_airbnb_df['price'])

0          966
1          142
3          368
4          204
7         1060
          ...
102041     946
102042     706
102043    1043
102044     809
102057    1128
Name: price, Length: 82735, dtype: int64

In [13]:
yearday_airbnb_df['service fee'] = yearday_airbnb_df['service fee'].str.replace("$","")
yearday_airbnb_df['service fee'] = yearday_airbnb_df['service fee'].str.replace(",","")
yearday_airbnb_df['service fee'] = pd.to_numeric(yearday_airbnb_df['service fee'])

C:\Users\divya\AppData\Local\Temp\ipykernel_34884\367740839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['service fee'] = yearday_airbnb_df['service fee'].str.replace("$","")
C:\Users\divya\AppData\Local\Temp\ipykernel_34884\367740839.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['service fee'] = yearday_airbnb_df['service fee'].str.replace(",","")
C:\Users\divya\AppData\Local\Temp\ipykernel_34884\367740839.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yearday_airbnb_df['service fee'] = pd.to_numeric(yearday_airbnb_df['service fee'])

In [15]:
yearday_airbnb_df['service fee']

0         193.0
1          28.0
3          74.0
4          41.0
7         212.0
          ...
102041    189.0
102042    141.0
102043    209.0
102044    162.0
102057      NaN
Name: service fee, Length: 82735, dtype: float64

In [17]:
yearday_airbnb_df['price'].dtypes

dtype('int64')

In [18]:
yearday_airbnb_df.to_csv("Resources/cleaned_airbnb_data.csv", index=False)